//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "brews")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub style: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub og: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub target_fg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub abv: Option<f64>,
    pub status: String,
    pub start_date: Option<DateTimeWithTimeZone>,
    pub end_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub hydrometer_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hydrometers::Entity",
        from = "Column::HydrometerId",
        to = "super::hydrometers::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Hydrometers,
    #[sea_orm(has_many = "super::readings::Entity")]
    Readings,
}

impl Related<super::hydrometers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hydrometers.def()
    }
}

impl Related<super::readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Readings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
