//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "hydrometers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub color: String,
    pub name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub temp_offset_f: f64,
    #[sea_orm(column_type = "Double")]
    pub gravity_offset: f64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::brews::Entity")]
    Brews,
    #[sea_orm(has_many = "super::readings::Entity")]
    Readings,
}

impl Related<super::brews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brews.def()
    }
}

impl Related<super::readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Readings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
