//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

#[allow(unused_imports)]
pub use super::brews::Entity as Brews;
#[allow(unused_imports)]
pub use super::hydrometers::Entity as Hydrometers;
#[allow(unused_imports)]
pub use super::readings::Entity as Readings;
