//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "readings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub brew_id: Option<Uuid>,
    pub hydrometer_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub temperature_f: f64,
    #[sea_orm(column_type = "Double")]
    pub gravity: f64,
    pub rssi: Option<i16>,
    pub recorded_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brews::Entity",
        from = "Column::BrewId",
        to = "super::brews::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Brews,
    #[sea_orm(
        belongs_to = "super::hydrometers::Entity",
        from = "Column::HydrometerId",
        to = "super::hydrometers::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Hydrometers,
}

impl Related<super::brews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brews.def()
    }
}

impl Related<super::hydrometers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hydrometers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
